### ISSUE TITLE
Not an issue. Just something I found in the web regarding exhaust valve controlling.

### ISSUE THREAD

**Issue by Xantorhd** [superwofy/E9X-M-CAN-Integration-Module#1]
Hey superwofy,

as stated in the title I found something special. I don't know whether you are interested but it's worth sharing imo.

It seems like the Exhaust valve is controlled via (I guess) PT-CAN. Message ID would be "0x6F1". Found it here:

https://f80.bimmerpost.com/forums/showthread.php?t=1366350

It's a good read. It only forces it open though. Must be a way to force it shut as well. I know it's for an F series M car but maybe BMW built that upon the existing logic on E series cars.

Hope this helps as it would be an oem+ route rather than depinning and installing a diode to control.

Cheers!

**Comment by superwofy** [comment]
Apologies, I forgot to reply to this.

I did see and consider this prior but did not implement it because of a note in the IKM0S DME function manual.
It would indeed make the hardware simpler, I'd love to get rid of the transistor.

```
The flag LV_AD_DIS_EXT_ADJ is set when an external adustment is done. The flag is set back to zero
at ECU reset. 
```

What I believe this implies is that for the particular drive cycle where you call this, the DME will no longer create adaptations. That's not a concession I'm willing to make.

Adjustments are SID 30_xx_07h diagnostic jobs.
Controlling the exhaust flap is done with: 30_C2_07. See page 7466.

Control OPEN (for 255 seconds):
0x12, 0x30, 0xC2, 0x07, 0xFF, 1, 0xFF, 0

Control CLOSED (for 255 seconds):
0x12, 0x30, 0xC2, 0x07, 0xFF, 0, 0xFF, 0

(More or less. I did not test it, this is based on what the manual says.)
